import "./index.scss";
import "./js/pages/home";
import "./js/pages/catalogue";
import "./js/pages/about";
import "./js/pages/portfolio"
import "./js/pages/project-detail";
import "./js/pages/product";
import "./js/pages/zastroyshikam";
import "./js/pages/request";
import "./js/components/header";
import "./js/components/range";
import "./js/components/footer";
import "./js/components/modal";
import "./js/components/portfolio-section-swiper";
import "./js/components/review-section-swiper";
import "./js/components/switcher";
import "./js/components/map";
